binance:
  key:
  secret:

martingala:
  originalAmount: 5000
  baseAmount: 100
  automaticThreshold: false
  decrease: 0.02
  baseCurrency: USDT
  limitToInitialInvestment: false
  minutesToBuyAgain: 5
#  tradingCurrency: SUSHI, TRB, YFI, RUNE, WNXM #Best for the 2020
#  tradingCurrency: BQX, SNX, BAND, SOL, SRM #2nds Best for the 2020
#  tradingCurrency: KSM, COMP, DOT, BAL, GAS #3rds Best for the 2020
#  tradingCurrency: XVS,REEF,ASR,ALPHA,GLM # The best ones for the first quarter of 2021
  tradingCurrency: THETA,DOT,NANO,LINK,XTZ,XVS,REEF,ASR
  interval: DAILY
  from: 2021-01-01
  to: 2021-03-01
  comission: 0.001

pump-strategy:
  quick:
    timeout: 600000
    benefitPercent: 2
    lossPercent: -5
    purchaseAmount: 0.0001

pump-detector:
  minTrades: 10
  minBuys: 0
  maxBuyerRatio: 0.2
  volumeRatio: 5000
  timeToDetect: 200
  symbols:
    - ETHBTC
    - MCOBTC
    - WTCBTC
    - LRCBTC
    - QTUMBTC
    - YOYOBTC
    - OMGBTC
    - ZRXBTC
    - STRATBTC
    - SNGLSBTC
    - BQXBTC
    - KNCBTC
    - FUNBTC
    - SNMBTC
    - IOTABTC
    - XVGBTC
    - SALTBTC
    - MDABTC
    - MTLBTC
    - SUBBTC
    - EOSBTC
    - SNTBTC
    - ETCBTC
    - MTHBTC
    - ENGBTC
    - DNTBTC
    - BNTBTC
    - ASTBTC
    - OAXBTC
    - ICNBTC
    - BTGBTC
    - EVXBTC
    - REQBTC
    - VIBBTC
    - TRXBTC
    - POWRBTC
    - ARKBTC
    - XRPBTC
    - MODBTC
    - ENJBTC
    - STORJBTC
    - VENBTC
    - KMDBTC
    - RCNBTC
    - NULSBTC
    - RDNBTC
    - DLTBTC
    - AMBBTC
    - BATBTC
    - BCPTBTC
    - ARNBTC
    - GVTBTC
    - CDTBTC
    - GXSBTC
    - POEBTC
    - QSPBTC
    - BTSBTC
    - XZCBTC
    - LSKBTC
    - TNTBTC
    - FUELBTC
    - MANABTC
    - BCDBTC
    - ADXBTC
    - ADABTC
    - PPTBTC
    - CMTBTC
    - XLMBTC
    - CNDBTC
    - LENDBTC
    - WABIBTC
    - TNBBTC
    - WAVESBTC
    - GTOBTC
    - ICXBTC
    - OSTBTC
    - ELFBTC
    - AIONBTC
    - NEBLBTC
    - BRDBTC
    - EDOBTC
    - WINGSBTC
    - NAVBTC
    - LUNBTC
    - TRIGBTC
    - APPCBTC
    - VIBEBTC
    - RLCBTC
    - INSBTC
    - PIVXBTC
    - IOSTBTC
    - CHATBTC
    - STEEMBTC
    - NANOBTC
    - VIABTC
    - BLZBTC
    - AEBTC
    - RPXBTC
    - NCASHBTC
    - POABTC
    - ZILBTC
    - ONTBTC
    - STORMBTC
    - XEMBTC
    - WANBTC
    - WPRBTC
    - QLCBTC
    - SYSBTC
    - GRSBTC
    - CLOAKBTC
    - GNTBTC
    - LOOMBTC
    - BCNBTC
    - TUSDBTC
    - SKYBTC
    - CVCBTC
    - THETABTC
    - IOTXBTC
    - QKCBTC
    - AGIBTC
    - NXSBTC
    - DATABTC
    - SCBTC
    - NPXSBTC
    - KEYBTC
    - NASBTC
    - MFTBTC
    - DENTBTC
    - ARDRBTC
    - HOTBTC
    - VETBTC
    - DOCKBTC
    - POLYBTC
    - PHXBTC
    - HCBTC
    - GOBTC
    - PAXBTC
    - RVNBTC
    - MITHBTC
    - RENBTC
    - BTTBTC
    - ONGBTC
    - FETBTC
    - CELRBTC
    - MATICBTC
    - ATOMBTC
    - PHBBTC
    - TFUELBTC
    - ONEBTC
    - FTMBTC
    - ALGOBTC
    - ERDBTC
    - DOGEBTC
    - DUSKBTC
    - ANKRBTC
    - WINBTC
    - COSBTC
    - COCOSBTC
    - TOMOBTC
    - PERLBTC
    - CHZBTC
    - BANDBTC
    - BEAMBTC
    - XTZBTC
    - HBARBTC
    - NKNBTC
    - STXBTC
    - KAVABTC
    - ARPABTC
    - CTXCBTC
    - TROYBTC
    - VITEBTC
    - FTTBTC
    - OGNBTC
    - DREPBTC
    - TCTBTC
    - WRXBTC
    - LTOBTC
    - MBLBTC
    - COTIBTC
    - STPTBTC
    - SOLBTC
    - CTSIBTC
    - HIVEBTC
    - CHRBTC
    - MDTBTC
    - STMXBTC
    - PNTBTC
    - DGBBTC
    - SXPBTC
    - SNXBTC
    - IRISBTC
    - DAIBTC
    - RUNEBTC
    - FIOBTC
    - AVABTC
    - JSTBTC
    - SRMBTC
    - ANTBTC
    - CRVBTC
    - SANDBTC
    - OCEANBTC
    - DOTBTC
    - LUNABTC
    - IDEXBTC
    - RSRBTC
    - BZRXBTC
    - SUSHIBTC
    - DIABTC
    - BELBTC
    - UNIBTC
    - NBSBTC
    - OXTBTC
    - SUNBTC
    - HNTBTC
    - FLMBTC
    - SCRTBTC
    - ORNBTC
    - UTKBTC
    - ALPHABTC
    - VIDTBTC
    - NEARBTC
    - INJBTC
    - AERGOBTC
    - AUDIOBTC
    - CTKBTC
    - AKROBTC
    - AXSBTC
    - HARDBTC
    - STRAXBTC
    - FORBTC
    - UNFIBTC
    - ROSEBTC
    - SKLBTC
    - SUSDBTC
    - GLMBTC
    - GRTBTC
    - JUVBTC
    - PSGBTC
    - 1INCHBTC
    - REEFBTC
    - OGBTC
    - ATMBTC
    - ASRBTC
    - CELOBTC
    - RIFBTC
    - TRUBTC
    - CKBBTC
    - TWTBTC
    - FIROBTC
    - LITBTC
    - SFPBTC